### ISSUE TITLE
Conpade error "Index was outside the bounds of the array"

### ISSUE THREAD

**Issue by manjumoorthy95** [gramarga/ConPADE#4]
Dear team,

The following error is being generated when Conpade is being executed in a Windows OS, on a BAM file of around 4 Gb size. The bam file has been marked for duplicates and sorted as well.

Error :

_```
Started contig NODE_1_length_68708_cov_7.368594 at 9/1/2022 2:50:49 AM

Unhandled Exception: System.Exception: Run failure. ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ConPADE.Read.LocateRead()
   at ConPADE.ConPADE.SearchReads(BAMParser parser, SAMAlignedSequence& nextAlignment, String contigName, Int64& numberOfAlignedReads, Int64& numberOfAlignedBasePairs, Int64& numberOfUsedReads, Int64& numberOfUsedBasePairs, Queue`1 readQueue, Int64 currentPos)
   at ConPADE.ConPADE.RunFile(String bamName)
   at ConPADE.ConPADE.RunTasks(RangeCollection tasksToRun, Int64 taskCount)
   at Bio.Util.Distribute.Locally.Distribute(IDistributable distributableObject)
   at Bio.Util.Distribute.SelfDistributable.Run()
   at Bio.Util.ArgumentParser.ArgumentCollection.ConstructAndRun[T](Boolean allowRepeats)
   --- End of inner exception stack trace ---
   at Bio.Util.ArgumentParser.ArgumentCollection.ConstructAndRun[T](Boolean allowRepeats)
   at Bio.Util.ArgumentParser.CommandArguments.ConstructAndRun[T](String[] commandArgs, Boolean allowRepeats)
   at ConPADE.ConPADE.Main(String[] args)
```_

Is is possible to detect what is the issue with the BAM file? 

Thanks,

Manju M

**Comment by gramarga** [comment]
Dear Manju,
Thank you for letting us know about this issue.

I suppose you have already validated the BAM file with something like GATK or BamUtil, correct?
Is it sorted by coordinate, not by read name?

If everything is correct with the BAM file, would you please be able to break it into smaller chunks and see where exactly the issue happens? Does it work with only the first read in the file? Can you identify an individual read that causes this problem?

Best regards,
Gabriel
